version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abasda
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    volumes:
      - type: bind
        source: ./data
        target: /data/db